grasps:
  # - grasp_id: "hand_H_v2-mujoco_box-grasp_0"
  #   object_id: "mujoco_box"
  #   hand_id: "hand_H_v2"
  #   manipulator_id: "fh_manipulator_ee"
  #   angle_units: radians
  #   pre_grasp_posture: [-0.78, -0.1, 0, 0.0, -1.34, 0.94, 0.78, -0.1, 0]
  #   grasp_posture: [-0.78, 0.31, -0.29, 0.0, -1.34, 0.94, 0.78, 0.31, -0.29]
  #   squeeze_direction: [0, 1, 0.6, 0, 0, 0, 0, 1, 0.6]
  #   pre_grasp_approach:
  #     direction:
  #       vector:
  #         x: 0.0
  #         y: 0.0
  #         z: -1.0
  #     desired_distance: 0.15
  #   post_grasp_retreat:
  #     direction:
  #       vector:
  #         x: 0.0
  #         y: 0.0
  #         z: -1.0
  #     desired_distance: 0.40
  #   post_place_retreat:
  #     direction:
  #       vector:
  #         x: 0.0
  #         y: 0.0
  #         z: -1.0
  #     desired_distance: 0.40
  #   grasp_pose:
  #     position:
  #       x: 0.023
  #       y: 0.0
  #       z: 0.14
  #     orientation:
  #       x: 0.707
  #       y: 0.707
  #       z: 0.0
  #       w: 0.0
  # - grasp_id: "hand_H_v2-mujoco_box-grasp_1"
  #   object_id: "mujoco_box"
  #   hand_id: "hand_H_v2"
  #   manipulator_id: "fh_manipulator_ee"
  #   angle_units: radians
  #   pre_grasp_posture: [-0.78, 0.2, -0.2, 0.0, -1.34, 0.94, 0.78, 0.2, -0.2]
  #   grasp_posture: [-0.78, 0.53, -0.45, 0.0, -1.34, 0.94, 0.78, 0.53, -0.45]
  #   squeeze_direction: [0, 1, 0.6, 0, 0, 0, 0, 1, 0.6]
  #   pre_grasp_approach:
  #     direction:
  #       vector:
  #         x: 0.0
  #         y: -1.0
  #         z: 0.0
  #     desired_distance: 0.25
  #   post_grasp_retreat:
  #     direction:
  #       vector:
  #         x: 0.0
  #         y: -1.0
  #         z: 0.0
  #     desired_distance: 0.40
  #   post_place_retreat:
  #     direction:
  #       vector:
  #         x: 0.0
  #         y: -1.0
  #         z: 0.0
  #     desired_distance: 0.40
  #   grasp_pose:
  #     position:
  #       x: 0.023
  #       y: 0.135
  #       z: 0.0
  #     orientation:
  #       x: 0.5
  #       y: 0.5
  #       z: -0.5
  #       w: 0.5
  - grasp_id: "hand_H_v2-mujoco_box-grasp_2"
    object_id: "mujoco_box"
    hand_id: "hand_H_v2"
    manipulator_id: "fh_manipulator_ee"
    angle_units: radians
    pre_grasp_posture: [-0.78, 0.2, -0.2, 0.0, -1.34, 0.94, 0.78, 0.2, -0.2]
    grasp_posture: [-0.78, 0.53, -0.45, 0.0, -1.34, 0.94, 0.78, 0.53, -0.45]
    squeeze_direction: [0, 1, 0.6, 0, 0, 0, 0, 1, 0.6]
    pre_grasp_approach:
      direction:
        vector:
          x: 1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.30
    post_grasp_retreat:
      direction:
        vector:
          x: 1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.40
    post_place_retreat:
      direction:
        vector:
          x: 1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.40
    grasp_pose:
      position:
        x: -0.16
        y: 0.023
        z: 0.0
      orientation:
        x: 0.0
        y: 0.707
        z: 0.0
        w: 0.707
