grasps:
  - grasp_id: "hand_H_v2-utl5_small-grasp_0"
    object_id: "utl5_small"
    hand_id: "hand_H_v2"
    manipulator_id: "fh_manipulator_ee"
    angle_units: radians
    pre_grasp_posture: [-0.78, 0.60, -0.62, 0.00, 0.95, -0.2, 0.78, 0.60, -0.62]
    grasp_posture: [-0.78, 0.85, -0.9, 0.00, 0.95, -0.2, 0.78, 0.85, -0.9]
    squeeze_direction: [0, 1, 0.6, 0, 0, 0, 0, 1, 0.6]
    pre_grasp_approach:
      direction:
        vector:
          x: 0.0
          y: 0.0
          z: -1.0
      desired_distance: 0.15
    post_grasp_retreat:
      direction:
        vector:
          x: 0.0
          y: 0.0
          z: -1.0
      desired_distance: 0.40
    post_place_retreat:
      direction:
        vector:
          x: 0.0
          y: 0.0
          z: -1.0
      desired_distance: 0.40
    grasp_pose:
      position:
        x: 0.023
        y: 0.0
        z: 0.1225
      orientation:
        x: 0.707
        y: 0.707
        z: 0.0
        w: 0.0
  - grasp_id: "hand_H_v2-utl5_small-grasp_1"
    object_id: "utl5_small"
    hand_id: "hand_H_v2"
    manipulator_id: "fh_manipulator_ee"
    angle_units: radians
    pre_grasp_posture: [-0.78, 0.66, -0.62, 0.0, -1.34, 0.94, 0.78, 0.66, -0.62]
    grasp_posture: [-0.78, 0.94, -0.94, 0.0, -1.34, 0.94, 0.78, 0.94, -0.94]
    squeeze_direction: [0, 1, 0.6, 0, 0, 0, 0, 1, 0.6]
    pre_grasp_approach:
      direction:
        vector:
          x: 0.0
          y: -1.0
          z: 0.0
      desired_distance: 0.15
    post_grasp_retreat:
      direction:
        vector:
          x: 0.0
          y: -1.0
          z: 0.0
      desired_distance: 0.40
    post_place_retreat:
      direction:
        vector:
          x: 0.0
          y: -1.0
          z: 0.0
      desired_distance: 0.40
    grasp_pose:
      position:
        x: 0.023
        y: 0.11
        z: 0.0
      orientation:
        x: 0.5
        y: 0.5
        z: -0.5
        w: 0.5
  - grasp_id: "hand_H_v2-utl5_small-grasp_2"
    object_id: "utl5_small"
    hand_id: "hand_H_v2"
    manipulator_id: "fh_manipulator_ee"
    angle_units: radians
    pre_grasp_posture: [-0.78, 0.66, -0.62, 0.0, -1.34, 0.94, 0.78, 0.66, -0.62]
    grasp_posture: [-0.78, 0.94, -0.94, 0.0, -1.34, 0.94, 0.78, 0.94, -0.94]
    squeeze_direction: [0, 1, 0.6, 0, 0, 0, 0, 1, 0.6]
    pre_grasp_approach:
      direction:
        vector:
          x: 1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.15
    post_grasp_retreat:
      direction:
        vector:
          x: 1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.40
    post_place_retreat:
      direction:
        vector:
          x: 1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.40
    grasp_pose:
      position:
        x: -0.10
        y: 0.023
        z: 0.0
      orientation:
        x: 0.0
        y: 0.707
        z: 0.0
        w: 0.707
  - grasp_id: "hand_H_v2-utl5_medium-grasp_0"
    object_id: "utl5_medium"
    hand_id: "hand_H_v2"
    manipulator_id: "fh_manipulator_ee"
    angle_units: radians
    pre_grasp_posture: [-0.78, 0.0, -0.25, 0.0, -1.34, 0.94, 0.78, 0.0, -0.25]
    grasp_posture: [-0.78, 0.50, -0.52, 0.0, -1.34, 0.94, 0.78, 0.50, -0.52]
    squeeze_direction: [0, 1, 0.6, 0, 0, 0, 0, 1, 0.6]
    pre_grasp_approach:
      direction:
        vector:
          x: 0.0
          y: 0.0
          z: -1.0
      desired_distance: 0.15
    post_grasp_retreat:
      direction:
        vector:
          x: 0.0
          y: 0.0
          z: -1.0
      desired_distance: 0.40
    post_place_retreat:
      direction:
        vector:
          x: 0.0
          y: 0.0
          z: -1.0
      desired_distance: 0.40
    grasp_pose:
      position:
        x: 0.023
        y: 0.00
        z: 0.135
      orientation:
        x: 0.707
        y: 0.707
        z: 0.0
        w: 0.0
  - grasp_id: "hand_H_v2-utl5_medium-grasp_1"
    object_id: "utl5_medium"
    hand_id: "hand_H_v2"
    manipulator_id: "fh_manipulator_ee"
    angle_units: radians
    pre_grasp_posture: [-0.78, 0.3, -0.4, 0.0, -1.34, 0.94, 0.78, 0.3, -0.4]
    grasp_posture: [-0.78, 0.74, -0.65, 0.0, -1.34, 0.94, 0.78, 0.74, -0.65]
    squeeze_direction: [0, 1, 0.6, 0, 0, 0, 0, 1, 0.6]
    pre_grasp_approach:
      direction:
        vector:
          x: 0.0
          y: -1.0
          z: 0.0
      desired_distance: 0.15
    post_grasp_retreat:
      direction:
        vector:
          x: 0.0
          y: -1.0
          z: 0.0
      desired_distance: 0.40
    post_place_retreat:
      direction:
        vector:
          x: 0.0
          y: -1.0
          z: 0.0
      desired_distance: 0.40
    grasp_pose:
      position:
        x: 0.023
        y: 0.13
        z: 0.0
      orientation:
        x: 0.5
        y: 0.5
        z: -0.5
        w: 0.5
  - grasp_id: "hand_H_v2-utl5_medium-grasp_2"
    object_id: "utl5_medium"
    hand_id: "hand_H_v2"
    manipulator_id: "fh_manipulator_ee"
    angle_units: radians
    pre_grasp_posture: [-0.78, 0.3, -0.4, 0.0, -1.34, 0.94, 0.78, 0.3, -0.4]
    grasp_posture: [-0.78, 0.74, -0.65, 0.0, -1.34, 0.94, 0.78, 0.74, -0.65]
    squeeze_direction: [0, 1, 0.6, 0, 0, 0, 0, 1, 0.6]
    pre_grasp_approach:
      direction:
        vector:
          x: 1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20
    post_grasp_retreat:
      direction:
        vector:
          x: 1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.40
    post_place_retreat:
      direction:
        vector:
          x: 1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.40
    grasp_pose:
      position:
        x: -0.176
        y: 0.023
        z: 0.0
      orientation:
        x: 0.0
        y: 0.707
        z: 0.0
        w: 0.707
  - grasp_id: "hand_H_v2-utl5_large-grasp_0"
    object_id: "utl5_large"
    hand_id: "hand_H_v2"
    manipulator_id: "fh_manipulator_ee"
    angle_units: radians
    pre_grasp_posture: [-0.78, -0.1, 0, 0.0, -1.34, 0.94, 0.78, -0.1, 0]
    grasp_posture: [-0.78, 0.31, -0.29, 0.0, -1.34, 0.94, 0.78, 0.31, -0.29]
    squeeze_direction: [0, 1, 0.6, 0, 0, 0, 0, 1, 0.6]
    pre_grasp_approach:
      direction:
        vector:
          x: 0.0
          y: 0.0
          z: -1.0
      desired_distance: 0.15
    post_grasp_retreat:
      direction:
        vector:
          x: 0.0
          y: 0.0
          z: -1.0
      desired_distance: 0.40
    post_place_retreat:
      direction:
        vector:
          x: 0.0
          y: 0.0
          z: -1.0
      desired_distance: 0.40
    grasp_pose:
      position:
        x: 0.023
        y: 0.0
        z: 0.14
      orientation:
        x: 0.707
        y: 0.707
        z: 0.0
        w: 0.0
  - grasp_id: "hand_H_v2-utl5_large-grasp_1"
    object_id: "utl5_large"
    hand_id: "hand_H_v2"
    manipulator_id: "fh_manipulator_ee"
    angle_units: radians
    pre_grasp_posture: [-0.78, 0.2, -0.2, 0.0, -1.34, 0.94, 0.78, 0.2, -0.2]
    grasp_posture: [-0.78, 0.53, -0.45, 0.0, -1.34, 0.94, 0.78, 0.53, -0.45]
    squeeze_direction: [0, 1, 0.6, 0, 0, 0, 0, 1, 0.6]
    pre_grasp_approach:
      direction:
        vector:
          x: 0.0
          y: -1.0
          z: 0.0
      desired_distance: 0.25
    post_grasp_retreat:
      direction:
        vector:
          x: 0.0
          y: -1.0
          z: 0.0
      desired_distance: 0.40
    post_place_retreat:
      direction:
        vector:
          x: 0.0
          y: -1.0
          z: 0.0
      desired_distance: 0.40
    grasp_pose:
      position:
        x: 0.023
        y: 0.135
        z: 0.0
      orientation:
        x: 0.5
        y: 0.5
        z: -0.5
        w: 0.5
  - grasp_id: "hand_H_v2-utl5_large-grasp_2"
    object_id: "utl5_large"
    hand_id: "hand_H_v2"
    manipulator_id: "fh_manipulator_ee"
    angle_units: radians
    pre_grasp_posture: [-0.78, 0.2, -0.2, 0.0, -1.34, 0.94, 0.78, 0.2, -0.2]
    grasp_posture: [-0.78, 0.53, -0.45, 0.0, -1.34, 0.94, 0.78, 0.53, -0.45]
    squeeze_direction: [0, 1, 0.6, 0, 0, 0, 0, 1, 0.6]
    pre_grasp_approach:
      direction:
        vector:
          x: 1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.30
    post_grasp_retreat:
      direction:
        vector:
          x: 1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.40
    post_place_retreat:
      direction:
        vector:
          x: 1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.40
    grasp_pose:
      position:
        x: -0.16
        y: 0.023
        z: 0.0
      orientation:
        x: 0.0
        y: 0.707
        z: 0.0
        w: 0.707
