mujoco_ros_control/pid_gains:
  ra_shoulder_pan_joint: {p: 1.0, i: 0.0, d: 1.0}
  ra_shoulder_lift_joint: {p: 1.0, i: 0.0, d: 1.0}
  ra_elbow_joint: {p: 1.0, i: 0.0, d: 1.0}
  ra_wrist_1_joint: {p: 1.0, i: 0.0, d: 1.0}
  ra_wrist_2_joint: {p: 1.0, i: 0.0, d: 1.0}
  ra_wrist_3_joint: {p: 1.0, i: 0.0, d: 1.0}
  